language: ruby
sudo: false

rvm:
  - 2.4.0
  - 2.5.0
  - 2.6.1

gemfile:
  - Gemfile_ar41
  - Gemfile_ar50
  - Gemfile_ar51
  - Gemfile_ar_master

matrix:
  fast_finish: true
  allow_failures:
    - rvm: 2.4.0
      gemfile: Gemfile_ar_master
    - rvm: 2.5.0
      gemfile: Gemfile_ar_master
    - rvm: 2.6.1
      gemfile: Gemfile_ar_master
