language: ruby

rvm:
  - 2.4
  - 2.5
  - 2.6
  - 2.7

gemfile:
  - Gemfile_ar41
  - Gemfile_ar50
  - Gemfile_ar51
  - Gemfile_ar_master

matrix:
  fast_finish: true
  exclude:
    - rvm: 2.7
      gemfile: Gemfile_ar41
  allow_failures:
    - rvm: 2.4
      gemfile: Gemfile_ar_master
    - rvm: 2.5
      gemfile: Gemfile_ar_master
    - rvm: 2.6
      gemfile: Gemfile_ar_master
    - rvm: 2.7
      gemfile: Gemfile_ar_master
